// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Vavsab.Zitadel
{
    /// <summary>
    /// Resource representing an OIDC application belonging to a project, with all configuration possibilities.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Zitadel = Vavsab.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var applicationOidc = new Zitadel.ApplicationOidc("applicationOidc", new()
    ///     {
    ///         ProjectId = zitadel_project.Project.Id,
    ///         OrgId = zitadel_org.Org.Id,
    ///         RedirectUris = new[]
    ///         {
    ///             "https://localhost.com",
    ///         },
    ///         ResponseTypes = new[]
    ///         {
    ///             "OIDC_RESPONSE_TYPE_CODE",
    ///         },
    ///         GrantTypes = new[]
    ///         {
    ///             "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
    ///         },
    ///         PostLogoutRedirectUris = new[]
    ///         {
    ///             "https://localhost.com",
    ///         },
    ///         AppType = "OIDC_APP_TYPE_WEB",
    ///         AuthMethodType = "OIDC_AUTH_METHOD_TYPE_BASIC",
    ///         Version = "OIDC_VERSION_1_0",
    ///         ClockSkew = "0s",
    ///         DevMode = true,
    ///         AccessTokenType = "OIDC_TOKEN_TYPE_BEARER",
    ///         AccessTokenRoleAssertion = false,
    ///         IdTokenRoleAssertion = false,
    ///         IdTokenUserinfoAssertion = false,
    ///         AdditionalOrigins = new[] {},
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/applicationOidc:ApplicationOidc")]
    public partial class ApplicationOidc : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Access token role assertion
        /// </summary>
        [Output("accessTokenRoleAssertion")]
        public Output<bool?> AccessTokenRoleAssertion { get; private set; } = null!;

        /// <summary>
        /// Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        /// </summary>
        [Output("accessTokenType")]
        public Output<string?> AccessTokenType { get; private set; } = null!;

        /// <summary>
        /// Additional origins
        /// </summary>
        [Output("additionalOrigins")]
        public Output<ImmutableArray<string>> AdditionalOrigins { get; private set; } = null!;

        /// <summary>
        /// App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        /// </summary>
        [Output("appType")]
        public Output<string?> AppType { get; private set; } = null!;

        /// <summary>
        /// Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        /// </summary>
        [Output("authMethodType")]
        public Output<string?> AuthMethodType { get; private set; } = null!;

        /// <summary>
        /// generated ID for this config
        /// </summary>
        [Output("clientId")]
        public Output<string> ClientId { get; private set; } = null!;

        /// <summary>
        /// generated secret for this config
        /// </summary>
        [Output("clientSecret")]
        public Output<string> ClientSecret { get; private set; } = null!;

        /// <summary>
        /// Clockskew
        /// </summary>
        [Output("clockSkew")]
        public Output<string?> ClockSkew { get; private set; } = null!;

        /// <summary>
        /// Dev mode
        /// </summary>
        [Output("devMode")]
        public Output<bool?> DevMode { get; private set; } = null!;

        /// <summary>
        /// Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH_TOKEN
        /// </summary>
        [Output("grantTypes")]
        public Output<ImmutableArray<string>> GrantTypes { get; private set; } = null!;

        /// <summary>
        /// ID token role assertion
        /// </summary>
        [Output("idTokenRoleAssertion")]
        public Output<bool?> IdTokenRoleAssertion { get; private set; } = null!;

        /// <summary>
        /// Token userinfo assertion
        /// </summary>
        [Output("idTokenUserinfoAssertion")]
        public Output<bool?> IdTokenUserinfoAssertion { get; private set; } = null!;

        /// <summary>
        /// Name of the application
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// orgID of the application
        /// </summary>
        [Output("orgId")]
        public Output<string> OrgId { get; private set; } = null!;

        /// <summary>
        /// Post logout redirect URIs
        /// </summary>
        [Output("postLogoutRedirectUris")]
        public Output<ImmutableArray<string>> PostLogoutRedirectUris { get; private set; } = null!;

        /// <summary>
        /// ID of the project
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// RedirectURIs
        /// </summary>
        [Output("redirectUris")]
        public Output<ImmutableArray<string>> RedirectUris { get; private set; } = null!;

        /// <summary>
        /// Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        /// </summary>
        [Output("responseTypes")]
        public Output<ImmutableArray<string>> ResponseTypes { get; private set; } = null!;

        /// <summary>
        /// Version, supported values: OIDC*VERSION*1_0
        /// </summary>
        [Output("version")]
        public Output<string?> Version { get; private set; } = null!;


        /// <summary>
        /// Create a ApplicationOidc resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApplicationOidc(string name, ApplicationOidcArgs args, CustomResourceOptions? options = null)
            : base("zitadel:index/applicationOidc:ApplicationOidc", name, args ?? new ApplicationOidcArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApplicationOidc(string name, Input<string> id, ApplicationOidcState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/applicationOidc:ApplicationOidc", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/vavsab",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApplicationOidc resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApplicationOidc Get(string name, Input<string> id, ApplicationOidcState? state = null, CustomResourceOptions? options = null)
        {
            return new ApplicationOidc(name, id, state, options);
        }
    }

    public sealed class ApplicationOidcArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access token role assertion
        /// </summary>
        [Input("accessTokenRoleAssertion")]
        public Input<bool>? AccessTokenRoleAssertion { get; set; }

        /// <summary>
        /// Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        /// </summary>
        [Input("accessTokenType")]
        public Input<string>? AccessTokenType { get; set; }

        [Input("additionalOrigins")]
        private InputList<string>? _additionalOrigins;

        /// <summary>
        /// Additional origins
        /// </summary>
        public InputList<string> AdditionalOrigins
        {
            get => _additionalOrigins ?? (_additionalOrigins = new InputList<string>());
            set => _additionalOrigins = value;
        }

        /// <summary>
        /// App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        /// </summary>
        [Input("appType")]
        public Input<string>? AppType { get; set; }

        /// <summary>
        /// Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        /// </summary>
        [Input("authMethodType")]
        public Input<string>? AuthMethodType { get; set; }

        /// <summary>
        /// Clockskew
        /// </summary>
        [Input("clockSkew")]
        public Input<string>? ClockSkew { get; set; }

        /// <summary>
        /// Dev mode
        /// </summary>
        [Input("devMode")]
        public Input<bool>? DevMode { get; set; }

        [Input("grantTypes", required: true)]
        private InputList<string>? _grantTypes;

        /// <summary>
        /// Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH_TOKEN
        /// </summary>
        public InputList<string> GrantTypes
        {
            get => _grantTypes ?? (_grantTypes = new InputList<string>());
            set => _grantTypes = value;
        }

        /// <summary>
        /// ID token role assertion
        /// </summary>
        [Input("idTokenRoleAssertion")]
        public Input<bool>? IdTokenRoleAssertion { get; set; }

        /// <summary>
        /// Token userinfo assertion
        /// </summary>
        [Input("idTokenUserinfoAssertion")]
        public Input<bool>? IdTokenUserinfoAssertion { get; set; }

        /// <summary>
        /// Name of the application
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// orgID of the application
        /// </summary>
        [Input("orgId", required: true)]
        public Input<string> OrgId { get; set; } = null!;

        [Input("postLogoutRedirectUris")]
        private InputList<string>? _postLogoutRedirectUris;

        /// <summary>
        /// Post logout redirect URIs
        /// </summary>
        public InputList<string> PostLogoutRedirectUris
        {
            get => _postLogoutRedirectUris ?? (_postLogoutRedirectUris = new InputList<string>());
            set => _postLogoutRedirectUris = value;
        }

        /// <summary>
        /// ID of the project
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        [Input("redirectUris", required: true)]
        private InputList<string>? _redirectUris;

        /// <summary>
        /// RedirectURIs
        /// </summary>
        public InputList<string> RedirectUris
        {
            get => _redirectUris ?? (_redirectUris = new InputList<string>());
            set => _redirectUris = value;
        }

        [Input("responseTypes", required: true)]
        private InputList<string>? _responseTypes;

        /// <summary>
        /// Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        /// </summary>
        public InputList<string> ResponseTypes
        {
            get => _responseTypes ?? (_responseTypes = new InputList<string>());
            set => _responseTypes = value;
        }

        /// <summary>
        /// Version, supported values: OIDC*VERSION*1_0
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ApplicationOidcArgs()
        {
        }
        public static new ApplicationOidcArgs Empty => new ApplicationOidcArgs();
    }

    public sealed class ApplicationOidcState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access token role assertion
        /// </summary>
        [Input("accessTokenRoleAssertion")]
        public Input<bool>? AccessTokenRoleAssertion { get; set; }

        /// <summary>
        /// Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        /// </summary>
        [Input("accessTokenType")]
        public Input<string>? AccessTokenType { get; set; }

        [Input("additionalOrigins")]
        private InputList<string>? _additionalOrigins;

        /// <summary>
        /// Additional origins
        /// </summary>
        public InputList<string> AdditionalOrigins
        {
            get => _additionalOrigins ?? (_additionalOrigins = new InputList<string>());
            set => _additionalOrigins = value;
        }

        /// <summary>
        /// App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        /// </summary>
        [Input("appType")]
        public Input<string>? AppType { get; set; }

        /// <summary>
        /// Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        /// </summary>
        [Input("authMethodType")]
        public Input<string>? AuthMethodType { get; set; }

        /// <summary>
        /// generated ID for this config
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// generated secret for this config
        /// </summary>
        [Input("clientSecret")]
        public Input<string>? ClientSecret { get; set; }

        /// <summary>
        /// Clockskew
        /// </summary>
        [Input("clockSkew")]
        public Input<string>? ClockSkew { get; set; }

        /// <summary>
        /// Dev mode
        /// </summary>
        [Input("devMode")]
        public Input<bool>? DevMode { get; set; }

        [Input("grantTypes")]
        private InputList<string>? _grantTypes;

        /// <summary>
        /// Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH_TOKEN
        /// </summary>
        public InputList<string> GrantTypes
        {
            get => _grantTypes ?? (_grantTypes = new InputList<string>());
            set => _grantTypes = value;
        }

        /// <summary>
        /// ID token role assertion
        /// </summary>
        [Input("idTokenRoleAssertion")]
        public Input<bool>? IdTokenRoleAssertion { get; set; }

        /// <summary>
        /// Token userinfo assertion
        /// </summary>
        [Input("idTokenUserinfoAssertion")]
        public Input<bool>? IdTokenUserinfoAssertion { get; set; }

        /// <summary>
        /// Name of the application
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// orgID of the application
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        [Input("postLogoutRedirectUris")]
        private InputList<string>? _postLogoutRedirectUris;

        /// <summary>
        /// Post logout redirect URIs
        /// </summary>
        public InputList<string> PostLogoutRedirectUris
        {
            get => _postLogoutRedirectUris ?? (_postLogoutRedirectUris = new InputList<string>());
            set => _postLogoutRedirectUris = value;
        }

        /// <summary>
        /// ID of the project
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        [Input("redirectUris")]
        private InputList<string>? _redirectUris;

        /// <summary>
        /// RedirectURIs
        /// </summary>
        public InputList<string> RedirectUris
        {
            get => _redirectUris ?? (_redirectUris = new InputList<string>());
            set => _redirectUris = value;
        }

        [Input("responseTypes")]
        private InputList<string>? _responseTypes;

        /// <summary>
        /// Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        /// </summary>
        public InputList<string> ResponseTypes
        {
            get => _responseTypes ?? (_responseTypes = new InputList<string>());
            set => _responseTypes = value;
        }

        /// <summary>
        /// Version, supported values: OIDC*VERSION*1_0
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ApplicationOidcState()
        {
        }
        public static new ApplicationOidcState Empty => new ApplicationOidcState();
    }
}
