// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Vavsab.Zitadel
{
    /// <summary>
    /// Resource representing the membership of a user on an instance, defined with the given role.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Zitadel = Vavsab.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var instanceMember = new Zitadel.InstanceMember("instanceMember", new()
    ///     {
    ///         UserId = zitadel_human_user.Human_user.Id,
    ///         Roles = new[]
    ///         {
    ///             "IAM_OWNER",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/instanceMember:InstanceMember")]
    public partial class InstanceMember : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
        /// </summary>
        [Output("roles")]
        public Output<ImmutableArray<string>> Roles { get; private set; } = null!;

        /// <summary>
        /// ID of the user
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a InstanceMember resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public InstanceMember(string name, InstanceMemberArgs args, CustomResourceOptions? options = null)
            : base("zitadel:index/instanceMember:InstanceMember", name, args ?? new InstanceMemberArgs(), MakeResourceOptions(options, ""))
        {
        }

        private InstanceMember(string name, Input<string> id, InstanceMemberState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/instanceMember:InstanceMember", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/vavsab",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing InstanceMember resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static InstanceMember Get(string name, Input<string> id, InstanceMemberState? state = null, CustomResourceOptions? options = null)
        {
            return new InstanceMember(name, id, state, options);
        }
    }

    public sealed class InstanceMemberArgs : global::Pulumi.ResourceArgs
    {
        [Input("roles", required: true)]
        private InputList<string>? _roles;

        /// <summary>
        /// List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Input("userId", required: true)]
        public Input<string> UserId { get; set; } = null!;

        public InstanceMemberArgs()
        {
        }
        public static new InstanceMemberArgs Empty => new InstanceMemberArgs();
    }

    public sealed class InstanceMemberState : global::Pulumi.ResourceArgs
    {
        [Input("roles")]
        private InputList<string>? _roles;

        /// <summary>
        /// List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public InstanceMemberState()
        {
        }
        public static new InstanceMemberState Empty => new InstanceMemberState();
    }
}
