// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Zitadel = scoretechnologies.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @default = new Zitadel.UserMetadata("default", new()
    ///     {
    ///         OrgId = data.Zitadel_org.Default.Id,
    ///         UserId = data.Zitadel_human_user.Default.Id,
    ///         Key = "a_key",
    ///         Value = "a_value",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// bash The resource can be imported using the ID format `&lt;user_id:key[:org_id]&gt;`, e.g.
    /// 
    /// ```sh
    ///  $ pulumi import zitadel:index/userMetadata:UserMetadata imported '123456789012345678:a_key:123456789012345678'
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/userMetadata:UserMetadata")]
    public partial class UserMetadata : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The key of a metadata entry
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Output("orgId")]
        public Output<string?> OrgId { get; private set; } = null!;

        /// <summary>
        /// ID of the user
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;

        /// <summary>
        /// The string representation of a metadata entry value. For binary data, use the base64encode function.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a UserMetadata resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserMetadata(string name, UserMetadataArgs args, CustomResourceOptions? options = null)
            : base("zitadel:index/userMetadata:UserMetadata", name, args ?? new UserMetadataArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserMetadata(string name, Input<string> id, UserMetadataState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/userMetadata:UserMetadata", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/scoretechnologies",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserMetadata resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserMetadata Get(string name, Input<string> id, UserMetadataState? state = null, CustomResourceOptions? options = null)
        {
            return new UserMetadata(name, id, state, options);
        }
    }

    public sealed class UserMetadataArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key of a metadata entry
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Input("userId", required: true)]
        public Input<string> UserId { get; set; } = null!;

        /// <summary>
        /// The string representation of a metadata entry value. For binary data, use the base64encode function.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public UserMetadataArgs()
        {
        }
        public static new UserMetadataArgs Empty => new UserMetadataArgs();
    }

    public sealed class UserMetadataState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key of a metadata entry
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        /// <summary>
        /// The string representation of a metadata entry value. For binary data, use the base64encode function.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public UserMetadataState()
        {
        }
        public static new UserMetadataState Empty => new UserMetadataState();
    }
}
