// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Vavsab.Zitadel
{
    /// <summary>
    /// Resource representing the authorization given to a user directly, including the given roles.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Zitadel = Vavsab.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var userGrant = new Zitadel.UserGrant("userGrant", new()
    ///     {
    ///         ProjectId = zitadel_project.Project.Id,
    ///         OrgId = zitadel_org.Org.Id,
    ///         RoleKeys = new[]
    ///         {
    ///             "key",
    ///         },
    ///         UserId = zitadel_human_user.Granted_human_user.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/userGrant:UserGrant")]
    public partial class UserGrant : global::Pulumi.CustomResource
    {
        /// <summary>
        /// ID of the organization which owns the resource
        /// </summary>
        [Output("orgId")]
        public Output<string> OrgId { get; private set; } = null!;

        /// <summary>
        /// ID of the granted project
        /// </summary>
        [Output("projectGrantId")]
        public Output<string?> ProjectGrantId { get; private set; } = null!;

        /// <summary>
        /// ID of the project
        /// </summary>
        [Output("projectId")]
        public Output<string?> ProjectId { get; private set; } = null!;

        /// <summary>
        /// List of roles granted
        /// </summary>
        [Output("roleKeys")]
        public Output<ImmutableArray<string>> RoleKeys { get; private set; } = null!;

        /// <summary>
        /// ID of the user
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a UserGrant resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserGrant(string name, UserGrantArgs args, CustomResourceOptions? options = null)
            : base("zitadel:index/userGrant:UserGrant", name, args ?? new UserGrantArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserGrant(string name, Input<string> id, UserGrantState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/userGrant:UserGrant", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/vavsab",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserGrant resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserGrant Get(string name, Input<string> id, UserGrantState? state = null, CustomResourceOptions? options = null)
        {
            return new UserGrant(name, id, state, options);
        }
    }

    public sealed class UserGrantArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the organization which owns the resource
        /// </summary>
        [Input("orgId", required: true)]
        public Input<string> OrgId { get; set; } = null!;

        /// <summary>
        /// ID of the granted project
        /// </summary>
        [Input("projectGrantId")]
        public Input<string>? ProjectGrantId { get; set; }

        /// <summary>
        /// ID of the project
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        [Input("roleKeys")]
        private InputList<string>? _roleKeys;

        /// <summary>
        /// List of roles granted
        /// </summary>
        public InputList<string> RoleKeys
        {
            get => _roleKeys ?? (_roleKeys = new InputList<string>());
            set => _roleKeys = value;
        }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Input("userId", required: true)]
        public Input<string> UserId { get; set; } = null!;

        public UserGrantArgs()
        {
        }
        public static new UserGrantArgs Empty => new UserGrantArgs();
    }

    public sealed class UserGrantState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the organization which owns the resource
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        /// <summary>
        /// ID of the granted project
        /// </summary>
        [Input("projectGrantId")]
        public Input<string>? ProjectGrantId { get; set; }

        /// <summary>
        /// ID of the project
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        [Input("roleKeys")]
        private InputList<string>? _roleKeys;

        /// <summary>
        /// List of roles granted
        /// </summary>
        public InputList<string> RoleKeys
        {
            get => _roleKeys ?? (_roleKeys = new InputList<string>());
            set => _roleKeys = value;
        }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public UserGrantState()
        {
        }
        public static new UserGrantState Empty => new UserGrantState();
    }
}
