// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Datasource representing the default oidc settings.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.LookupDefaultOidcSettings(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("oidcSettings", _default)
//			return nil
//		})
//	}
//
// ```
func LookupDefaultOidcSettings(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupDefaultOidcSettingsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupDefaultOidcSettingsResult
	err := ctx.Invoke("zitadel:index/getDefaultOidcSettings:getDefaultOidcSettings", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDefaultOidcSettings.
type LookupDefaultOidcSettingsResult struct {
	// lifetime duration of access tokens
	AccessTokenLifetime string `pulumi:"accessTokenLifetime"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// lifetime duration of id tokens
	IdTokenLifetime string `pulumi:"idTokenLifetime"`
	// expiration duration of refresh tokens
	RefreshTokenExpiration string `pulumi:"refreshTokenExpiration"`
	// expiration duration of idle refresh tokens
	RefreshTokenIdleExpiration string `pulumi:"refreshTokenIdleExpiration"`
}
