// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Datasource representing an Azure AD IDP on the instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-zitadel/sdk/go/zitadel"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/pulumiverse/pulumi-zitadel/sdk/go/zitadel"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := zitadel.LookupIdpAzureAd(ctx, &GetIdpAzureAdArgs{
// 			Id: "177073614158299139",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupIdpAzureAd(ctx *pulumi.Context, args *LookupIdpAzureAdArgs, opts ...pulumi.InvokeOption) (*LookupIdpAzureAdResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupIdpAzureAdResult
	err := ctx.Invoke("zitadel:index/getIdpAzureAd:getIdpAzureAd", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIdpAzureAd.
type LookupIdpAzureAdArgs struct {
	// The ID of this resource.
	Id string `pulumi:"id"`
}

// A collection of values returned by getIdpAzureAd.
type LookupIdpAzureAdResult struct {
	// client id generated by the identity provider
	ClientId string `pulumi:"clientId"`
	// client secret generated by the identity provider
	ClientSecret string `pulumi:"clientSecret"`
	// automatically mark emails as verified
	EmailVerified bool `pulumi:"emailVerified"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// enabled if a new account in ZITADEL are created automatically on login with an external account
	IsAutoCreation bool `pulumi:"isAutoCreation"`
	// enabled if a the ZITADEL account fields are updated automatically on each login
	IsAutoUpdate bool `pulumi:"isAutoUpdate"`
	// enabled if users are able to create a new account in ZITADEL when using an external account
	IsCreationAllowed bool `pulumi:"isCreationAllowed"`
	// enabled if users are able to link an existing ZITADEL user with an external account
	IsLinkingAllowed bool `pulumi:"isLinkingAllowed"`
	// Name of the IDP
	Name string `pulumi:"name"`
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes []string `pulumi:"scopes"`
	// the azure ad tenant id
	TenantId string `pulumi:"tenantId"`
	// the azure ad tenant type
	TenantType string `pulumi:"tenantType"`
}

func LookupIdpAzureAdOutput(ctx *pulumi.Context, args LookupIdpAzureAdOutputArgs, opts ...pulumi.InvokeOption) LookupIdpAzureAdResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIdpAzureAdResult, error) {
			args := v.(LookupIdpAzureAdArgs)
			r, err := LookupIdpAzureAd(ctx, &args, opts...)
			var s LookupIdpAzureAdResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIdpAzureAdResultOutput)
}

// A collection of arguments for invoking getIdpAzureAd.
type LookupIdpAzureAdOutputArgs struct {
	// The ID of this resource.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupIdpAzureAdOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIdpAzureAdArgs)(nil)).Elem()
}

// A collection of values returned by getIdpAzureAd.
type LookupIdpAzureAdResultOutput struct{ *pulumi.OutputState }

func (LookupIdpAzureAdResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIdpAzureAdResult)(nil)).Elem()
}

func (o LookupIdpAzureAdResultOutput) ToLookupIdpAzureAdResultOutput() LookupIdpAzureAdResultOutput {
	return o
}

func (o LookupIdpAzureAdResultOutput) ToLookupIdpAzureAdResultOutputWithContext(ctx context.Context) LookupIdpAzureAdResultOutput {
	return o
}

// client id generated by the identity provider
func (o LookupIdpAzureAdResultOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) string { return v.ClientId }).(pulumi.StringOutput)
}

// client secret generated by the identity provider
func (o LookupIdpAzureAdResultOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) string { return v.ClientSecret }).(pulumi.StringOutput)
}

// automatically mark emails as verified
func (o LookupIdpAzureAdResultOutput) EmailVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) bool { return v.EmailVerified }).(pulumi.BoolOutput)
}

// The ID of this resource.
func (o LookupIdpAzureAdResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) string { return v.Id }).(pulumi.StringOutput)
}

// enabled if a new account in ZITADEL are created automatically on login with an external account
func (o LookupIdpAzureAdResultOutput) IsAutoCreation() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) bool { return v.IsAutoCreation }).(pulumi.BoolOutput)
}

// enabled if a the ZITADEL account fields are updated automatically on each login
func (o LookupIdpAzureAdResultOutput) IsAutoUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) bool { return v.IsAutoUpdate }).(pulumi.BoolOutput)
}

// enabled if users are able to create a new account in ZITADEL when using an external account
func (o LookupIdpAzureAdResultOutput) IsCreationAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) bool { return v.IsCreationAllowed }).(pulumi.BoolOutput)
}

// enabled if users are able to link an existing ZITADEL user with an external account
func (o LookupIdpAzureAdResultOutput) IsLinkingAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) bool { return v.IsLinkingAllowed }).(pulumi.BoolOutput)
}

// Name of the IDP
func (o LookupIdpAzureAdResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) string { return v.Name }).(pulumi.StringOutput)
}

// the scopes requested by ZITADEL during the request on the identity provider
func (o LookupIdpAzureAdResultOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) []string { return v.Scopes }).(pulumi.StringArrayOutput)
}

// the azure ad tenant id
func (o LookupIdpAzureAdResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) string { return v.TenantId }).(pulumi.StringOutput)
}

// the azure ad tenant type
func (o LookupIdpAzureAdResultOutput) TenantType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAzureAdResult) string { return v.TenantType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIdpAzureAdResultOutput{})
}
