name: Upgrade upstream provider
on:
  workflow_dispatch:

  # TODO: remove this
  pull_request:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      # - name: Call upgrade provider action
      #   uses: pulumi/pulumi-upgrade-provider-action@v0.0.6
      #   with:
      #     kind: bridge
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
        shell: bash
      - name: Install upgrade-provider
        run: go install github.com/pulumi/upgrade-provider@main
        shell: bash
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "7.6"
      - name: Set up git identity
        run: git config --global user.name 'vavsab'
        shell: bash
      - name: Run upgrade-provider
        run: upgrade-provider ${{ github.repository }} --kind=bridge
        shell: bash
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}


