name: Upgrade upstream provider
on:
  workflow_dispatch:

  # TODO: remove this
  pull_request:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@v0.0.6
        with:
          kind: bridge


