// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Datasource representing a human user situated under an organization, which then can be authorized through memberships or direct grants on other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@pulumi/zitadel";
 *
 * const default = zitadel.getHumanUser({
 *     orgId: data.zitadel_org["default"].id,
 *     userId: "123456789012345678",
 * });
 * export const humanUser = _default;
 * ```
 */
export function getHumanUser(args: GetHumanUserArgs, opts?: pulumi.InvokeOptions): Promise<GetHumanUserResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zitadel:index/getHumanUser:getHumanUser", {
        "orgId": args.orgId,
        "userId": args.userId,
    }, opts);
}

/**
 * A collection of arguments for invoking getHumanUser.
 */
export interface GetHumanUserArgs {
    /**
     * ID of the organization
     */
    orgId: string;
    /**
     * The ID of this resource.
     */
    userId: string;
}

/**
 * A collection of values returned by getHumanUser.
 */
export interface GetHumanUserResult {
    /**
     * Display name of the user
     */
    readonly displayName: string;
    /**
     * Email of the user
     */
    readonly email: string;
    /**
     * First name of the user
     */
    readonly firstName: string;
    /**
     * Gender of the user
     */
    readonly gender: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Is the email verified of the user, can only be true if password of the user is set
     */
    readonly isEmailVerified: boolean;
    /**
     * Is the phone verified of the user
     */
    readonly isPhoneVerified: boolean;
    /**
     * Last name of the user
     */
    readonly lastName: string;
    /**
     * Loginnames
     */
    readonly loginNames: string[];
    /**
     * Nick name of the user
     */
    readonly nickName: string;
    /**
     * ID of the organization
     */
    readonly orgId: string;
    /**
     * Phone of the user
     */
    readonly phone: string;
    /**
     * Preferred language of the user
     */
    readonly preferredLanguage: string;
    /**
     * Preferred login name
     */
    readonly preferredLoginName: string;
    /**
     * State of the user
     */
    readonly state: string;
    /**
     * The ID of this resource.
     */
    readonly userId: string;
    /**
     * Username
     */
    readonly userName: string;
}
/**
 * Datasource representing a human user situated under an organization, which then can be authorized through memberships or direct grants on other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@pulumi/zitadel";
 *
 * const default = zitadel.getHumanUser({
 *     orgId: data.zitadel_org["default"].id,
 *     userId: "123456789012345678",
 * });
 * export const humanUser = _default;
 * ```
 */
export function getHumanUserOutput(args: GetHumanUserOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHumanUserResult> {
    return pulumi.output(args).apply((a: any) => getHumanUser(a, opts))
}

/**
 * A collection of arguments for invoking getHumanUser.
 */
export interface GetHumanUserOutputArgs {
    /**
     * ID of the organization
     */
    orgId: pulumi.Input<string>;
    /**
     * The ID of this resource.
     */
    userId: pulumi.Input<string>;
}
