// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource representing the custom password complexity policy of an organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@pulumiverse/zitadel";
 *
 * const passwordComplexityPolicy = new zitadel.PasswordComplexityPolicy("passwordComplexityPolicy", {
 *     orgId: zitadel_org.org.id,
 *     minLength: 8,
 *     hasUppercase: true,
 *     hasLowercase: true,
 *     hasNumber: true,
 *     hasSymbol: true,
 * });
 * ```
 */
export class PasswordComplexityPolicy extends pulumi.CustomResource {
    /**
     * Get an existing PasswordComplexityPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PasswordComplexityPolicyState, opts?: pulumi.CustomResourceOptions): PasswordComplexityPolicy {
        return new PasswordComplexityPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zitadel:index/passwordComplexityPolicy:PasswordComplexityPolicy';

    /**
     * Returns true if the given object is an instance of PasswordComplexityPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PasswordComplexityPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PasswordComplexityPolicy.__pulumiType;
    }

    /**
     * defines if the password MUST contain a lower case letter
     */
    public readonly hasLowercase!: pulumi.Output<boolean>;
    /**
     * defines if the password MUST contain a number
     */
    public readonly hasNumber!: pulumi.Output<boolean>;
    /**
     * defines if the password MUST contain a symbol. E.g. "$"
     */
    public readonly hasSymbol!: pulumi.Output<boolean>;
    /**
     * defines if the password MUST contain an upper case letter
     */
    public readonly hasUppercase!: pulumi.Output<boolean>;
    /**
     * Minimal length for the password
     */
    public readonly minLength!: pulumi.Output<number>;
    /**
     * Id for the organization
     */
    public readonly orgId!: pulumi.Output<string>;

    /**
     * Create a PasswordComplexityPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PasswordComplexityPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PasswordComplexityPolicyArgs | PasswordComplexityPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PasswordComplexityPolicyState | undefined;
            resourceInputs["hasLowercase"] = state ? state.hasLowercase : undefined;
            resourceInputs["hasNumber"] = state ? state.hasNumber : undefined;
            resourceInputs["hasSymbol"] = state ? state.hasSymbol : undefined;
            resourceInputs["hasUppercase"] = state ? state.hasUppercase : undefined;
            resourceInputs["minLength"] = state ? state.minLength : undefined;
            resourceInputs["orgId"] = state ? state.orgId : undefined;
        } else {
            const args = argsOrState as PasswordComplexityPolicyArgs | undefined;
            if ((!args || args.hasLowercase === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hasLowercase'");
            }
            if ((!args || args.hasNumber === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hasNumber'");
            }
            if ((!args || args.hasSymbol === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hasSymbol'");
            }
            if ((!args || args.hasUppercase === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hasUppercase'");
            }
            if ((!args || args.minLength === undefined) && !opts.urn) {
                throw new Error("Missing required property 'minLength'");
            }
            if ((!args || args.orgId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'orgId'");
            }
            resourceInputs["hasLowercase"] = args ? args.hasLowercase : undefined;
            resourceInputs["hasNumber"] = args ? args.hasNumber : undefined;
            resourceInputs["hasSymbol"] = args ? args.hasSymbol : undefined;
            resourceInputs["hasUppercase"] = args ? args.hasUppercase : undefined;
            resourceInputs["minLength"] = args ? args.minLength : undefined;
            resourceInputs["orgId"] = args ? args.orgId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PasswordComplexityPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PasswordComplexityPolicy resources.
 */
export interface PasswordComplexityPolicyState {
    /**
     * defines if the password MUST contain a lower case letter
     */
    hasLowercase?: pulumi.Input<boolean>;
    /**
     * defines if the password MUST contain a number
     */
    hasNumber?: pulumi.Input<boolean>;
    /**
     * defines if the password MUST contain a symbol. E.g. "$"
     */
    hasSymbol?: pulumi.Input<boolean>;
    /**
     * defines if the password MUST contain an upper case letter
     */
    hasUppercase?: pulumi.Input<boolean>;
    /**
     * Minimal length for the password
     */
    minLength?: pulumi.Input<number>;
    /**
     * Id for the organization
     */
    orgId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PasswordComplexityPolicy resource.
 */
export interface PasswordComplexityPolicyArgs {
    /**
     * defines if the password MUST contain a lower case letter
     */
    hasLowercase: pulumi.Input<boolean>;
    /**
     * defines if the password MUST contain a number
     */
    hasNumber: pulumi.Input<boolean>;
    /**
     * defines if the password MUST contain a symbol. E.g. "$"
     */
    hasSymbol: pulumi.Input<boolean>;
    /**
     * defines if the password MUST contain an upper case letter
     */
    hasUppercase: pulumi.Input<boolean>;
    /**
     * Minimal length for the password
     */
    minLength: pulumi.Input<number>;
    /**
     * Id for the organization
     */
    orgId: pulumi.Input<string>;
}
