// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource representing the SMS provider Twilio configuration of an instance.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = new zitadel.SmsProviderTwilio("default", {
 *     senderNumber: "019920892",
 *     sid: "sid",
 *     token: "twilio_token",
 * });
 * ```
 *
 * ## Import
 *
 * bash The resource can be imported using the ID format `<id[:token]>`, e.g.
 *
 * ```sh
 *  $ pulumi import zitadel:index/smsProviderTwilio:SmsProviderTwilio imported '123456789012345678:12345678901234567890123456abcdef'
 * ```
 */
export class SmsProviderTwilio extends pulumi.CustomResource {
    /**
     * Get an existing SmsProviderTwilio resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SmsProviderTwilioState, opts?: pulumi.CustomResourceOptions): SmsProviderTwilio {
        return new SmsProviderTwilio(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zitadel:index/smsProviderTwilio:SmsProviderTwilio';

    /**
     * Returns true if the given object is an instance of SmsProviderTwilio.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SmsProviderTwilio {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SmsProviderTwilio.__pulumiType;
    }

    /**
     * Sender number which is used to send the SMS.
     */
    public readonly senderNumber!: pulumi.Output<string>;
    /**
     * SID used to communicate with Twilio.
     */
    public readonly sid!: pulumi.Output<string>;
    /**
     * Token used to communicate with Twilio.
     */
    public readonly token!: pulumi.Output<string>;

    /**
     * Create a SmsProviderTwilio resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SmsProviderTwilioArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SmsProviderTwilioArgs | SmsProviderTwilioState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SmsProviderTwilioState | undefined;
            resourceInputs["senderNumber"] = state ? state.senderNumber : undefined;
            resourceInputs["sid"] = state ? state.sid : undefined;
            resourceInputs["token"] = state ? state.token : undefined;
        } else {
            const args = argsOrState as SmsProviderTwilioArgs | undefined;
            if ((!args || args.senderNumber === undefined) && !opts.urn) {
                throw new Error("Missing required property 'senderNumber'");
            }
            if ((!args || args.sid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sid'");
            }
            if ((!args || args.token === undefined) && !opts.urn) {
                throw new Error("Missing required property 'token'");
            }
            resourceInputs["senderNumber"] = args ? args.senderNumber : undefined;
            resourceInputs["sid"] = args ? args.sid : undefined;
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SmsProviderTwilio.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SmsProviderTwilio resources.
 */
export interface SmsProviderTwilioState {
    /**
     * Sender number which is used to send the SMS.
     */
    senderNumber?: pulumi.Input<string>;
    /**
     * SID used to communicate with Twilio.
     */
    sid?: pulumi.Input<string>;
    /**
     * Token used to communicate with Twilio.
     */
    token?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SmsProviderTwilio resource.
 */
export interface SmsProviderTwilioArgs {
    /**
     * Sender number which is used to send the SMS.
     */
    senderNumber: pulumi.Input<string>;
    /**
     * SID used to communicate with Twilio.
     */
    sid: pulumi.Input<string>;
    /**
     * Token used to communicate with Twilio.
     */
    token: pulumi.Input<string>;
}
